@startuml

object Brewfile

object git
object ghq
object zsh

object dotfiles
object dotfilesInstall
object npmGlobal


' File
object ssh
object sshZip

' App
object 1Password
object DropBox

' Service
object GitHubPrivate

Brewfile->git
Brewfile->zsh
Brewfile->DropBox
Brewfile->1Password

sshZip->ssh
1Password->ssh

zsh->dotfilesInstall
ghq->dotfiles
git->ghq
DropBox->sshZip
ssh->GitHubPrivate

ghq->dotfilesInstall
dotfiles->dotfilesInstall

@enduml
