@startuml

object Brewfile

object git
object ghq
object zsh

object dotfiles
object dotfilesInstall
object npmGlobal


' File
object sshSetup

' App
object 1Password
object DropBox

' App config
object IntelliJAtomSetup

' Service
object GitHubPrivate

Brewfile->git
Brewfile->zsh
Brewfile->DropBox
Brewfile->1Password

1Password->sshSetup
1Password->DropBox

1Password->IntelliJAtomSetup

zsh->dotfilesInstall
ghq->dotfiles
git->ghq
DropBox->sshSetup
sshSetup->GitHubPrivate

GitHubPrivate->IntelliJAtomSetup
GitHubPrivate->npmGlobal

ghq->dotfilesInstall
dotfiles->dotfilesInstall

@enduml
